export interface WellCareCustomer {
  call_center_script_name: string;  // always "Wellcare"
  health_plan: string;              // e.g., "Wellcare of Alabama"
  practitioner_name: string;        // e.g., "JENNIFER NELSON"
  office_phone: string;             // digits only
  address: string;                  // full address
  practice_name: string;            // clinic/practice (from Provider_Name column)
  speciality: string;               // from Excel (N column)
}

export const wellCareCustomers: WellCareCustomer[] = [
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Alabama",
    practitioner_name: "TIMOTHY WHALEN",
    office_phone: "2563252627",
    address: "600 SUN TEMPLE DR, MADISON, AL 35758",
    practice_name: "NULL",
    speciality: "Behavioral Health",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Alabama",
    practitioner_name: "JENNIFER NELSON",
    office_phone: "2056189899",
    address: "109 FOOTHILLS PKWY STE 113, CHELSEA, AL 35043",
    practice_name: "KOLBE CLINIC LLC",
    speciality: "Behavioral Health",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Alabama",
    practitioner_name: "JONATHAN TODD",
    office_phone: "2516628000",
    address: "2419 GORDON SMITH DR, MOBILE, AL 36617",
    practice_name: "ALTAPOINTE HEALTH SYSTEMS INC",
    speciality: "Behavioral Health",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Alabama",
    practitioner_name: "GEORGE MELNYK",
    office_phone: "2568453150",
    address: "600 SUN TEMPLE DR, MADISON, AL 35758",
    practice_name: "INTEGRATED BEHAVIORAL HEALTH",
    speciality: "Behavioral Health",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Alabama",
    practitioner_name: "RACHEL HOADLEY-CLAUSEN",
    office_phone: "2516335125",
    address: "6720 GRELOT RD STE A, MOBILE, AL 36695",
    practice_name: "NEUROMUSCULAR SPINE AND JOINT CENTE ",
    speciality: "Behavioral Health",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Alabama",
    practitioner_name: "HARRISON PEARL",
    office_phone: "2519526659",
    address: "1711 N MCKENZIE ST STE 102, FOLEY, AL 36535",
    practice_name: " FOLEY CLINC CORP",
    speciality: "Behavioral Health",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Connecticut",
    practitioner_name: "KATHERINE ZAMECKI VEDDER",
    office_phone: "2032644002",
    address: "1449 OLD WATERBURY RD 1 RESERVOIR OFFICE PARK STE 203, SOUTHBURY, CT 06488",
    practice_name: "CONNECTICUT EYE CONSULTANTS P.C.",
    speciality: "Ophthalmologists",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Arkansas",
    practitioner_name: "ANDREA STILLWELL",
    office_phone: "5012364110",
    address: "110 PEARSON, BENTON, AR 72015",
    practice_name: "COUNSELING CLINIC INC",
    speciality: "Behavioral Health",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Arkansas",
    practitioner_name: "BALAGOPALAN NAIR",
    office_phone: "5019063000",
    address: "1601 N WEST AVE, EL DORADO, AR 71730",
    practice_name: "CENTRAL AR RADIATION THERAPY INSTIT",
    speciality: "Oncologists",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Arkansas",
    practitioner_name: "RICHARD WHITE",
    office_phone: "8705805280",
    address: "639 HOSPITAL DR, MOUNTAIN HOME, AR 72653",
    practice_name: "HIGHLANDS ONCOLOGY GROUP PA",
    speciality: "Oncologists",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Arkansas",
    practitioner_name: "DAVID PRUITT",
    office_phone: "5016222100",
    address: "1455 HIGDON FERRY RD STE C, HOT SPRINGS, AR 71913",
    practice_name: "HOT SPRINGS RADIATION ONCOLOGY",
    speciality: "Oncologists",
  },
  {
    call_center_script_name: "Wellcare",
    health_plan: "Wellcare of Arkansas",
    practitioner_name: "ANURADHA KUNTHUR",
    office_phone: "5016868000",
    address: "4301 W MARKHAM ST 783, LITTLE ROCK, AR 72205",
    practice_name: "MEDICAL COLLEGE PHYSICIANS GROUP",
    speciality: "Oncologists",
  },
  {
    call_center_script_name: "Wellcare of Arizona",
    health_plan: "Wellcare of Arizona",
    practitioner_name: "AHINOAM CHAVEZ",
    office_phone: "4806411165",
    address: "7565 E EAGLE CREST DR STE 101, MESA, AZ 85207",
    practice_name: " LIFELINE PROFESSIONAL COUNSELING SE ",
    speciality: "Behavioral Health",
  },
  {
    call_center_script_name: "Wellcare of Arizona",
    health_plan: "Wellcare of Arizona",
    practitioner_name: "PATRICK OUZTS",
    office_phone: "5209016350",
    address: "1521 E TANGERINE RD STE 315, ORO VALLEY, AZ 85741",
    practice_name: "NORTHWEST ALLIED PHYSICIANS LLC ",
    speciality: "PCP",
  },
];