name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    # Run on push or pull_request (except closed ones)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Step 1: Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Step 2: Adjust Git Permissions so the runner can update the config
      - name: Adjust Git Permissions
        run: sudo chown -R $USER:$USER .git

      # Step 3: Unset any extra headers that might cause issues
      - name: Unset Git extraheader
        run: git config --local --unset-all http.https://github.com/.extraheader || true

      # Step 4: Build and Deploy with Oryx
      - name: Build with Oryx and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "deploy"
          # Update these paths to match your project structure:
          app_location: "/"         # Your app source code folder
          api_location: ""          # Your API folder (if any, or leave empty)
          output_location: "build"  # The folder where your build output is generated

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
